version: "3.8"

services:
  postgresdb:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chaicode
    volumes:
      - postgres_data:/var/lib/postgresql/data

# You MUST declare the named volume at the root level down here
volumes:
  postgres_data:
